// Vue/breaking-bad/src/components/ui/Search.vue
<template>
  <section class="search">
    <form>
      <input
        type="text"
        class="form-control"
        placeholder="Search characters"
        v-model="value"
        autoFocus
        @input="onChange(value)"
      />
    </form>
  </section>
</template>

<script>
export default {
  props: {
    onChange: {
      type: Function
    }
  },
  data() {
    return {
      value: ''
    }
  }
}
</script>

<style></style>

// React/breaking-bad/src/components/ui/Search.js
import React, { useState } from 'react'

const Search = ({ getQuery }) => {
  const [text, setText] = useState('')

  const onChange = (value) => {
    setText(value)
    getQuery(value)
  }

  return (
    <section className="search">
      <form>
        <input
          type="text"
          className="form-control"
          placeholder="Search characters"
          value={text}
          onChange={(e) => onChange(e.target.value)}
          autoFocus
        />
      </form>
    </section>
  )
}

export default Search
