// React/hackernews-app/src/components/Search.js
import React from 'react'

const Search = ({ onChange, value, onSubmit, children }) => {
  return (
    <div>
      <form onSubmit={onSubmit}>
        <input type="text" onChange={onChange} value={value} />
        <button type="submit">{children}</button>
      </form>
    </div>
  )
}

export default Search

// Vue/breaking-bad/src/components/ui/Search.vue
<template>
  <section class="search">
    <form>
      <input
        type="text"
        class="form-control"
        placeholder="Search characters"
        v-model="value"
        autoFocus
        @input="onChange(value)"
      />
    </form>
  </section>
</template>

<script>
export default {
  props: {
    onChange: {
      type: Function
    }
  },
  data() {
    return {
      value: ''
    }
  }
}
</script>

<style></style>
